### ISSUE TITLE
RFC: Ability to filter reimbursements by a range of 'issue_date's

### ISSUE THREAD

**Issue by fgrehm** [datasciencebr/jarbas#101]
The other day I was playing with the flight tickets dataset and was able to identify tickets for international flights (basically check if the `total_net_value` is > 4k).

With that info we'd be able to identify a period of time when the congressperson was abroad and investigate reimbursements in Brazil that requires the deputy to be physically present (like taxi and meals).

I believe we have more important things to cover before getting to the point of automating the extraction of "period away from Brazil" data points BUT I'm willing to manually check some of those reimbursements to ensure it is worth the trouble to automate this in rosie in the future and for that it would be super helpful if jarbas could provide a search for the following filters in combination:

- issue_date_start
- issue_date_end
- congressperson_id (applicant_id might be enough as well)
- subquota_number

Dunno if it would be useful for other use cases so feel free to 👎 this issue 😄

**Comment by cuducos** [comment]
Closed by PR #106
