### ISSUE TITLE
Create dashboard with reports

### ISSUE THREAD

**Issue by flaviodrt** [datasciencebr/jarbas#111]
Hi,
I don't know if jarbas is the appropriate project for this funcionality, but I suggest to create a dashboard containing all reports informed to Chamber (https://twitter.com/cuducos/status/818434229314928641) and showing the information of each real invested in the project, how much was returned to society.
This funcionality is inspired in this article: http://www1.folha.uol.com.br/mercado/2017/01/1846255-jornalismo-investigativo-gera-lucro-para-a-sociedade-diz-diretor-de-stanford.shtml

**Comment by cuducos** [comment]
I'd say that's not Jarbas focus. Jarbas is a tool to visualize the reimbursements and data related to them. This kind of balance/report would have a better fit in a new version of [our website](serenata-website). Would you mind opening this issue there? cc @brunopazzim @vilapedro
