### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by glauberramos** [datasciencebr/jarbas#117]
It would be nice to have a CONTRIBUTING.md in order to know how to best contribute to the project.

**Comment by cuducos** [comment]
Cool… What would you add there, I mean… what's missing? The most obvious questions are already documented IMHO: how to install (`README.md`) and in which areas we need help (Issues). What else could we write on the `CONTRIBUTING.md`? Would you mind drafting something, an outline for example?

**Comment by glauberramos** [comment]
I was thinking more about it and it makes sense that we don't need it. I don't actually have questions about how to contribute but I am facing some issues on running the project with docker. Maybe if we detail more the issues that can happen, right now for example when I try to access localhost:80 it's saying Elm is not defined.

**Comment by glauberramos** [comment]
@gomex helped me fix that issue and I am running the app now 💃
