### ISSUE TITLE
Adapt front-end to be more stateless

### ISSUE THREAD

**Issue by cuducos** [datasciencebr/jarbas#122]
Nowadays passing information (`Language` basically everywhere, `parentId` for `RelatedTable` etc.) has proved too verbose (and adds unnecessary complexity — e.g. with `Html.map`). 

[This design](https://gist.github.com/rofrol/fd46e9570728193fddcc234094a0bd99#reusable-views-instead-of-nested-components) is more promising.

**Comment by rogeriochaves** [comment]
I can work on that, just played a bit with the code to remove Language from Inputs, and oh my god, it is so much simpler now, I can see a big refactor coming (:

I believe it will be easier if we merge #130 and #137 first (I've pulld the branch, much easier to work with docker :P)

**Comment by cuducos** [comment]
Great, that'd would be awesome — many thanks for the enthusiasm!

Just a bit of context around the PRs:

* I hope #127 is merged today: there was a bug in it, but hopefully I could fixed it — as soon as @gomex review it I can merge I guess
* #130 will be merged later today by @jtemporal or @anaschwendler I guess

If you wanna pair on this issue, just drop a line ; )

**Comment by cuducos** [comment]
Both done ; )

**Comment by cuducos** [comment]
I'm kind of waiting for progress on #61 so this architecture refactor can be part of the UI/UX refactor proposed there.
