### ISSUE TITLE
Store company activities as JSONField

### ISSUE THREAD

**Issue by cuducos** [datasciencebr/jarbas#124]
Nowadays each `Company` stores its main and secondary activities in a separate model (`Activity`) using a `ManyToManyField`.

I don't think it's necessary as we won't query by a company activity (at least not that frequently). Also this design makes the `python manage.py companies <companies.xz>` extremely slow because we cannot use `bulk_create` with relational tables (or can we?).

**Comment by Guilhermeslucas** [comment]
So, you're thinking to replace the activity model with a field on the companies model as JSON, with all the primary and secondary activities?

**Comment by cuducos** [comment]
Yes, that's it.

Basically we can (just drafting here, probably I've forgotten some steps, such as checking if Django REST Framework serializers are consistent with the new strategy etc.):

1. Edit `models.py` removing `Activity` and setting up `main_activity` and `secondary_activity` to `JSONField`
2. Create a migration ; )
3. Adapt the serializer inside `companies.py` to parse `main_activity` and `secondary_activity` as something like a list of `dict`s (eg. `[ {"code": "42", "description": "foo"}, {"code: "31415", "description": "bar"} ]`)
4. Use `bulk_create` (as in `reimbursements.xz`) to speed up the import of companies data

**Comment by cuducos** [comment]
An extra would be to manage data in the migrations, so we don't have to loose data and reimport it when moving along the migrations history…

**Comment by Guilhermeslucas** [comment]
Ok @cuducos. I'll give it a try. Now, to check these informations we check the /api/company/<cnpj>/ adress, right?

**Comment by cuducos** [comment]
Yep. To check this info you get to `/api/company/00000000000000/` where this tons of zeros is a CNPJ ; )

**Comment by Guilhermeslucas** [comment]
I changed the model an the Django REST Framework is fully working. But when I make a search on the index page of Jarbas, it doesn't show the campanies detail, as in the pictures above. Any idea on how to fix it?

Working REST Framework:
![captura de tela de 2017-01-18 00 58 38](https://cloud.githubusercontent.com/assets/9682164/22049278/6f904f2c-dd19-11e6-9c4e-f0f3cbf37e99.png)

Search not displaying companies information:
![captura de tela de 2017-01-18 00 58 53](https://cloud.githubusercontent.com/assets/9682164/22049279/76008e6c-dd19-11e6-969b-78d54d5b05dc.png)

**Comment by Guilhermeslucas** [comment]
I have a clue! Now, main and secondary activities are JSON, not a list(?) anymore.

**Comment by cuducos** [comment]
Are tests passing? I think you changed the way the API serves information. That is not necessary (and specially secondary activity actually needs to be an array).

If you find it difficult not to change the format currently in use I can pair to give you a hand, or you can suggest an edit on the Elm decoder that deals with this part of the API — check your browser's log console for some hints ; )

**Comment by Guilhermeslucas** [comment]
I'll try to keep the information the same way! Do you think itis better to change the way I save informations on JSON Field or the API code that throws JSON? Many thanks, @cuducos

**Comment by Guilhermeslucas** [comment]
It's fixed now :) Do you want me to open a PR now or to write the bulk create?

**Comment by Guilhermeslucas** [comment]
Sorry sending so much messages. Am I allowed to change the tests? It fails cause try to use the old Models, like activity, that don't exist anymore!

**Comment by cuducos** [comment]
> Do you think itis better to change the way I save informations on JSON Field or the API code that throws JSON?

I'd go for the first options for consistency. I believe it makes sense to be a list (a list of activities the company is involved with).

> Do you want me to open a PR now or to write the bulk create?

I'd vote for writing the `bulk_create` code as this is the main advantage of this changes ; )

> Am I allowed to change the tests? It fails cause try to use the old Models, like activity, that don't exist anymore!

Sure. If they don't fit the current scenario they have to be updated ; )

**Comment by Guilhermeslucas** [comment]
I'll work on it, then! thanks!

**Comment by cuducos** [comment]
If you want, you can work a WIP (_work in progress_) PR and we can give you feedback in your (partial) code. Just add _[WIP]_ to the title of the PR and I'll know it's not ready to merge ; )

But only if you want to. Some people prefer to wait and send a more elaborated PR and theres absolutely no problem. Either way I'm fine It's up to you.

**Comment by Guilhermeslucas** [comment]
I opened ad [WIP] PR #139 . If someone know more about tests than I do, I'd appreciate some help to make the coverage hit 100% again.

**Comment by cuducos** [comment]
The PR looks good. I'm gonna do a proper _code review_ soon. I believe we can discuss that in the PR page ; ) Many thaks, @guilhermeslucas!

**Comment by Guilhermeslucas** [comment]
@cuducos I don't know this is the right place, but I didn't find anywhere to ask this question. Since this issue looks like to be solved, is there some other issue I can work on? Many thanks,

**Comment by cuducos** [comment]
>  I don't know this is the right place, but I didn't find anywhere to ask this question.

Join us at the tech Telegram group (linked in the `CONTRIBUTION.md` within the [main repo](https://github.com/datasciencebr/serenata-de-amor)).

>  is there some other issue I can work on?

If you're enjoying Python, there is still [one Python related issue around here](https://github.com/datasciencebr/jarbas/issues/125). Otherwise there are open issues in the [other repositories](https://github.com/datasciencebr) that might be of interest ; )

**Comment by Guilhermeslucas** [comment]
Oh, the Telegram link, I'm already there. Sorry. I'll take a look at this issue. Again, thanks a lot! You guys are awesome.

**Comment by cuducos** [comment]
Closing this PR because storing it as JSON would make `CNPJ` filters _too slow_…
