### ISSUE TITLE
Error on Elm inside docker 

### ISSUE THREAD

**Issue by glauberramos** [datasciencebr/jarbas#134]
I'm facing this issue inside docker volume, whenever I change a elm file it gives this error.

<img width="468" alt="screen shot 2017-01-17 at 11 49 45 pm" src="https://cloud.githubusercontent.com/assets/559434/22047703/b873f932-dd0f-11e6-8b5f-3baf73bd21cb.png">

Any idea on how to fix it?

**Comment by cuducos** [comment]
Can you confirm your Elm files are compiling successfully _outside_ the Docker environment? If you're not sure, zip `jarbas/frontend/elm` and share it ; )

**Comment by glauberramos** [comment]
I cleaned everything (deleted code, docker containers, images and volumes). Still seeing this issue. If I run "gulp elm" on my local folder, it works fine. It looks like is only inside docker. Not sure what is happening.

Any idea @gomex ?

**Comment by glauberramos** [comment]
If I try "make build.elm", the same issue appears.

**Comment by cuducos** [comment]
Let me try to help you @glauberramos. You shared that running `gulp elm` in the local folder throws you no errors. What about the documented way to build assets: `yarn assets` (or even `npm run assets`), can you confirm this works?

This difference is important. When you run `gulp elm` you're using a `gulp` binary that is in your `$PATH`, which is **not** how this project is configured to work. We install `gulp` locally and only `yarn` (or `npm`) access the `gulp` binary in the `node_modules/.bin/` directory.

So, can you confirm that in the local environment it works so we can be sure that the issue is within the Docker setup?

**Comment by glauberramos** [comment]
In the it was me being noob on docker hehehe. I run "npm install" on my local, so docker was using elm binary compiled on mac os, but docker uses linux. I will add a instruction to not run "npm install" locally if you are using docker.

**Comment by teesloane** [comment]
@glauberramos 

I'm running into this now; could you share an example of the solution that you came up with?

**Comment by glauberramos** [comment]
@teesloane for me was cleaning everything (deleting the code, cleaning docker) and then I didn't run npm install on my machine, this was the issue with me.

**Comment by teesloane** [comment]
Ah ok, thanks for the quick response!

I definitely need to figure out how to properly clean and remove old docker images / containers and what not. 

So when you say "didn't run npm install on my machine" — you mean not running npm install within the folder where your are building the docker container from?

**Comment by glauberramos** [comment]
I think you can use https://kitematic.com/ (in case you use mac) to see all the containers. Here is a link that shows how to remove everything: https://www.digitalocean.com/community/tutorials/how-to-remove-docker-images-containers-and-volumes.

Yeah I mean not running "npm install" inside jarbas root folder on your machine itself (not on docker).

**Comment by teesloane** [comment]
Cool, thanks @glauberramos . 

I'm just wiping out all docker stuff; I'll try out kitematic. I'm glad I found this issue! I will keep working on this; hopefully I'll figure out my docker stuff (it's slowly but surely coming along...)

Thanks!!
