### ISSUE TITLE
API: /api/ is pointing to localhost

### ISSUE THREAD

**Issue by cuducos** [datasciencebr/jarbas#14]
Now it's: `{"document":"http://127.0.0.1:8001/api/document/"}`

It should be: `{"document":"http://jarbas.datasciencebr.com/api/document/"}`

Pagination links also have this bug.

**Comment by gwmoura** [comment]
@cuducos you tried this: http://www.django-rest-framework.org/api-guide/schemas/#adding-a-schema?

We can define a schema_url for the API - http://www.django-rest-framework.org/api-guide/schemas/#schema_url

**Comment by cuducos** [comment]
Tks @gwmoura — `proxy_set_header Host $host;` fixed it ; )

**Comment by gwmoura** [comment]
😉
