### ISSUE TITLE
Add tests for Elm

### ISSUE THREAD

**Issue by cuducos** [datasciencebr/jarbas#17]

**Comment by NicolasFrancaX** [comment]
You already have a idea of a test suite we can use?

**Comment by cuducos** [comment]
I'd suggest [elm-test](https://github.com/elm-community/elm-test) — I have a simple working example (including integration with Travis CI) at [Cunha já caiu?](https://github.com/cuducos/cunhajacaiu) if it helps. We can pair on that too.

**Comment by paulohp** [comment]
Is there anyone working on this? I want to help. @cuducos @NicolasFrancaX

**Comment by cuducos** [comment]
AFAIK no one, @paulohp…

**Comment by paulohp** [comment]
grabbing it then 😃

**Comment by cuducos** [comment]
Many thanks, Paulo!

Next week I might be available for pair programming, but don't hesitate to drop a line here if you have any doubt about the code and architecture ; )

**Comment by paulohp** [comment]
No Problem @cuducos 

I'm trying to setup the project  locally but I'm getting some errors.

1) Which python version are you using? I got some errors with lzma and I solved with https://github.com/peterjc/backports.lzma. My Python version = 3.5.2

2) I'm getting 404 on "GET /static/app.js?e66b0de8 HTTP/1.1" and blank screen on localhost:8000

Is there anything else to do besides the documentation on README.md ?

**Comment by cuducos** [comment]
Hi @paulohp… I'm sorry about that.

1. **`lzma`**: I found out about this issue in Linux yesterday (cc @andrepinho @filipelinhares) and haven't had time to properly explore and document it yet; anyway the thing is that when you compile your Python you must have `lzma` library available in your system. I'd say that it wasn't `backports.lzma` that fixed your issue, but the `apt-get install liblzma-dev` — however I have to make some tests in a VM before confirming it (anyone else please feel free to jump in and send a PR). BTW, the Python version we're using is 3.5 (gonna add to the `README.md` now).
1. This is surely related to your static files; have you noticed any error or warning when you ran `python manage.py collectstatic`? Also are you running it in `DEBUG` mode or not (Django serves static files differently in `DEBUG` mode)?

If you have a screen share utility drop a line and I can help you get started in the next hour.

**Comment by cuducos** [comment]
Regarding the issue with the static files: what's the output for `which elm-make`?

If `elm-make` is not available in your path, set [`ELM_MAKE_BIN`](https://github.com/cuducos/webassets-elm#requirements) environment to where `elm-make` binary is (probably `node_modules/.bin/elm-make` if you installed Elm locally).

**Comment by cuducos** [comment]
I created a brach to keep track of this issues, once I can confirm the instructions are correct I merge it to master — you all feel free to contribute: https://github.com/datasciencebr/jarbas/tree/install-instructions#requirements

**Comment by paulohp** [comment]
Hi @cuducos, no problem!

1) I solved `lzma`, it's not a problem anymore 😃 
2) I just set `DEBUG=true` and it's just working fine 👍 

```
➜  jarbas git:(master) which elm-make
/usr/local/bin/elm-make
```
