### ISSUE TITLE
Make links on the 'URL do Documento Fiscal' field clickable

### ISSUE THREAD

**Issue by brwolfgang** [datasciencebr/jarbas#186]
Currently you have to copy the link and paste on a new tab - a job that quickly grows tiresome if you are viewing multiple receipts in a row:
![image](https://cloud.githubusercontent.com/assets/3627736/26745782/48a81208-47ba-11e7-947d-9749b03afc1e.png)

Great work on the dashboard, btw.

**Comment by cuducos** [comment]
Many thanks, @brwolfgang! I'll add some stuff to this Issue as all of them are related to customizing the same part of Django Admin:

- [ ] Link receipt URL (as OP suggested)
- [ ] Show suspicions in pt_BR (not JSON)
- [ ] Show `subquota_description` in pt_BR (not en_US)

**Comment by jtemporal** [comment]
Just checking, we can close this right?

**Comment by cuducos** [comment]
Closed by #190
