### ISSUE TITLE
Load supplier information based on the CNPJ

### ISSUE THREAD

**Issue by cuducos** [datasciencebr/jarbas#2]

**Comment by leomeloxp** [comment]
Is there an API where this can be pulled from? I'd like to help with #8 but it depends on this being done.

**Comment by cuducos** [comment]
The idea is to use Serenata de Amor's [`data/YYYY-MM-DD-companies.xz`](https://github.com/datasciencebr/serenata-de-amor/blob/master/CONTRIBUTING.md#datasets-data) the same way we use the CEAP datasets (i.e. `data/YYYY-MM-DD-current-year.xz`, `data/YYYY-MM-DD-last-year.xz` and `data/YYYY-MM-DD-previous-years.xz`:

* Add the data structure to `jarbas/core/models.py`
* Create a Django [command](https://github.com/datasciencebr/jarbas#load-data) (e.g. [`jarbas/core/management/commands.py`](https://github.com/datasciencebr/jarbas/blob/master/jarbas/core/management/commands/loaddatasets.py)) to import this data from Serenata de Amor directory or server
* Allow [Django REST Framework](http://django-rest-framework.org) to serve data in the API
* Integrate this API in the `jarbas/frontend`

If nobody tackles it soon, this issue is actually my focus for this next week — if anyone would like to pair on that, please, let me know.

**Comment by cuducos** [comment]
Just a follow up. I'm deploying the [suppliers info to the JSON API](https://github.com/datasciencebr/jarbas#supplier). The UI part is still pending, but I'm gonna implement it soon.

**Comment by cuducos** [comment]
Currently there's no latitude/longitude info on the API. That's a bug.

**Comment by cuducos** [comment]
Closed after e0509f7
