### ISSUE TITLE
Add link to @RosieDaSerenata tweets

### ISSUE THREAD

**Issue by cuducos** [datasciencebr/jarbas#209]
A possible roadmap would be a custom Django command to scrap @RosieDaSerenata to:

- [x] Parse tweets and figure out the `document_id`<br>done in 65af517 @  [`cuducos-read-rosies-tweets`](https://github.com/datasciencebr/jarbas/tree/cuducos-read-rosies-tweets)
- [x] Check if tweet exists in Jarbas database<br>done in 6736039 @  [`cuducos-read-rosies-tweets`](https://github.com/datasciencebr/jarbas/tree/cuducos-read-rosies-tweets)
- [x] Save link to a new model (or add a field to `Reimbursement` model)<br>done in 6736039 @  [`cuducos-read-rosies-tweets`](https://github.com/datasciencebr/jarbas/tree/cuducos-read-rosies-tweets)
- [x] Write tests<br>done in f462cb1 & 6820cf0 @  [`cuducos-read-rosies-tweets`](https://github.com/datasciencebr/jarbas/tree/cuducos-read-rosies-tweets)
- [x] Add info to JSON API view<br>done in df042cb @  [`cuducos-read-rosies-tweets`](https://github.com/datasciencebr/jarbas/tree/cuducos-read-rosies-tweets)
- [x] Add a link in the UI (eg next to fetch/view receipt )<br>done in b7c145a @ [`cuducos-read-rosies-tweets`](https://github.com/datasciencebr/jarbas/tree/cuducos-read-rosies-tweets)
- [x] Add links in the dashboard<br>done in 4453e6d @ [`cuducos-read-rosies-tweets`](https://github.com/datasciencebr/jarbas/tree/cuducos-read-rosies-tweets)

**Comment by cuducos** [comment]
Working on it on [`https://github.com/datasciencebr/jarbas/tree/cuducos-read-rosies-tweets`](https://github.com/datasciencebr/jarbas/tree/cuducos-read-rosies-tweets) — feel free to check and open PR to this branch.

**Comment by Irio** [comment]
Check this out before working on the first item: [whistleblower/targets/twitter.py#L84](https://github.com/datasciencebr/whistleblower/blob/25c4c8932228143e61b0f8eb6a764aeabbaffa7a/whistleblower/targets/twitter.py#L84). Whistleblower maintains a database with `document_id`/`tweet_id`.

**Comment by cuducos** [comment]
> Whistleblower maintains a database with `document_id`/`tweet_id`

Does this MongoDB has a public accessible IP/domain, @Irio?
