### ISSUE TITLE
RFC: Add link to congressperson profile from reimbursement page

### ISSUE THREAD

**Issue by fgrehm** [datasciencebr/jarbas#220]
I think this is a quick win that can make it easier for rosie's followers on twitter to reach out to congresspeople as the data there contains most up to date deputies phone number and email

Example:
- https://jarbas.serenatadeamor.org/#/document_id/6155695
- Would link to http://www.camara.leg.br/Internet/Deputado/dep_Detalhe.asp?id=167722 (id == Congressperson ID)

**Comment by cuducos** [comment]
Closed by #247
