### ISSUE TITLE
Import receipts texts (from OCR)

### ISSUE THREAD

**Issue by cuducos** [datasciencebr/jarbas#222]
Adding OCR data (`2017-02-15-receipts-texts.xz`) to `Reimbursement` and adding it to the dashboard would make @tatianasb and @vilapedro lives easier: they could search in receipt text easily (without depending on any tech interface).

A possible roadmap:

1. Add a field to `Reimbursement` model
1. Add a command similar to the one that load suspicions
1. Add this field (and set is as searchable) in the admin/dashboard

**Comment by jtemporal** [comment]
- [ ] Add a field to Reimbursement model
- [ ] Add a command similar to the one that load suspicions
- [ ] Add this field (and set is as searchable) in the admin/dashboard
