### ISSUE TITLE
Use full text search on Django Admin

### ISSUE THREAD

**Issue by cuducos** [datasciencebr/jarbas#226]
#225 tried to add `receipt_text` as a searchable field in the admin. Unfortunately our production server couldn't handle this (probably crashing, high memory usage and stuff).  I pushed d2c280b as an emergency fix removing `receipt_text` from `search_fields` and throwing away the use case proposed by #222.

Thus we need to **try** [full text search](https://docs.djangoproject.com/en/1.11/ref/contrib/postgres/search/) to check if the production server can handle the query this way.

**Comment by luzfcb** [comment]
try put `@` [1] on start of field or override `get_search_results` [2] method.



```
class ReimbursementModelAdmin(SimpleHistoryAdmin):
    search_fields = (
            '@receipt_text',
        #...
    )
```

[1] https://github.com/django/django/blob/1.11.3/django/contrib/admin/options.py#L897-L898
[2] https://docs.djangoproject.com/en/1.11/ref/contrib/admin/#django.contrib.admin.ModelAdmin.get_search_results

**Comment by cuducos** [comment]
Thanks @luzfcb (and thanks @henriquebastos who helped me in PVT).

Maybe the `@` works, but exploring the `get_search_results` seems more promising because the text search uses more than one field (`receipt_text`, `congressperson_name`, `supplier` etc.).
