### ISSUE TITLE
Add link to receipt in the Jarbas Dashboard list view

### ISSUE THREAD

**Issue by cuducos** [datasciencebr/jarbas#250]
As we have links to Jarbas main view of the receipt, and for Rosie's tweet, we could add an icon so users can jump to the list view (eg home of Jarbas Dashboard) directly to a given receipt PDF.

**Comment by jtemporal** [comment]
Just to help visualize: it would have a 📄 kind of icon close to Jarbas "J" and the 🤖 in between "Reembolso" and "Nome do Parlamentar":

<img width="311" alt="screen shot 2017-09-19 at 10 44 17 am" src="https://user-images.githubusercontent.com/6595551/30595640-1fc4a2f2-9d28-11e7-9cd0-4fd25a269356.png">

**Comment by giovanisleite** [comment]
I can do it =))
