### ISSUE TITLE
The 'yes'/'no' dashboard filters

### ISSUE THREAD

**Issue by giovanisleite** [datasciencebr/jarbas#256]
Hi,

I was looking the pull request #254 (implementing the has_receipt_url filter that is like the suspicions), and now I am confuse about the operation of the filter.

How should these filters work?
e.g. "suspicions"
"All": shows all the reimbursements;
"Yes": Show only reimbursements that are suspect;
"No": Show only reimbursements that aren't suspect. Right?

So... why there isn't a query for the 'no'? Like `
return self.exclude(suspicions__isnull=True)
`?
for the 'no', returns just the queryset that is the same return for 'all' (ausence of value).

If I am right about this, there is a bug on the 'no' filter

Like [this](https://jarbas.serenatadeamor.org/dashboard/core/reimbursement/?month=12&state=SP&subquota_id=13&year=2016), using another filters just too see the number of results.
Filters that I used: Month: December, Year: 2016. State: SP. Subquota: 'Congressperson meal' (id 13).

Without suspicious filter (selected: 'All'): 259 results.
When I try 'yes' for suspicious, 1 result.
When I try 'no' for suspicious, 259 results. I think that isn't working, because should be 258 results (1 suspect + 258 that isn't suspect).

Am I missing something?

**Comment by cuducos** [comment]
That makes a lot of sense… you've found a bug ; )

My only comment would be `self.filer(suspicions=none)` instead of `self.exclude(suspicions__isnull=True)` ; )

**Comment by giovanisleite** [comment]
> you've found a bug , yay!

:beetle: hahaha

> My only comment would be self.filter(suspicions=None) instead of self.exclude(suspicions__isnull=True) ; )

Why? The query seems equal

**Comment by cuducos** [comment]
> Why? The query seems equal

They are not equal, they produce equal results.

```python
>>> import this
The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
[…]
```

[A double negative resolves to a positive](https://en.wikipedia.org/wiki/Double_negative#Two_negatives_resolving_to_a_positive) (_excluding_ what is _not_ `None` is filtering only what is `None`).  But [double negative arguably are confusing](http://www.scienceeditingexperts.com/why-double-negatives-are-so-confusing-in-scientific-writing) — i.e. less implicit (and _explicit is better than implicit_), less simple (and _simple is better than complex_), more difficult to read (and _readability counts_) and IMHO less beautiful (and _beautiful is better than ugly_) ; )

**Comment by giovanisleite** [comment]
I was looking for performance problems and checked the sql query
Now I see the problem, Thanks @cuducos
