### ISSUE TITLE
Add a Donate button to README

### ISSUE THREAD

**Issue by jtemporal** [datasciencebr/jarbas#258]
**What is the problem?**
We don't have a donate button 😱

**How can this be addressed?**
Add a button donate button to the README file

It something like ![donate](https://img.shields.io/badge/donate-apoia.se-EB4A3B.svg) linked with [Serenata's Apoia.se Campaign](https://apoia.se/serenata). I generated that badge with [Shields.io](https://shields.io/).

**Who could help with this issue?**
Anyone really

**Labels**
Already there 😉

**Important**
This is a [first-timers-only issue](http://www.firsttimersonly.com/), it is supposed to help people get their feet wet. Keep that in mind when considering to open a pull request 😉

**Comment by jtemporal** [comment]
Code for the badge mentioned: `![donate](https://img.shields.io/badge/donate-apoia.se-EB4A3B.svg)`

**Comment by Ilozuluchris** [comment]
Hello jtemporal,so am guessing the button links to the donate button at https://apoia.se/serenata (the green button on the page).I would like to try this

**Comment by jtemporal** [comment]
go ahead @Ilozuluchris 😉

**Comment by ivanzaqqa** [comment]
i want to contribute with this @jtemporal

**Comment by cuducos** [comment]
Closed by #259 — thanks everybody for the enthusiasm, luckily there's [a lot of other issues](https://github.com/datasciencebr/jarbas/labels/hacktoberfest) around ; )
