### ISSUE TITLE
The refactored docker image broke celery?

### ISSUE THREAD

**Issue by giovanisleite** [datasciencebr/jarbas#289]
Hey folks,

I am having problems to load the sample data

![image](https://user-images.githubusercontent.com/11703235/33300474-ad217b44-d3d7-11e7-9a11-0a9a6edd71da.png)

The #285 introduced a new api to docker and seems that all commands are preceded by `python manage.py`, but that was supposed to happen on tasks too?
Looks like tasks are trying to use the command `celery worker --app jarbas` and getting `python manage.py celery worker --app jarbas`.

I was able to use the celery workers/tasks, just running `docker-compose exec -d  tasks celery worker --app jarbas`

Am I doing something wrong?
Thanks.

**Comment by cuducos** [comment]
Hum… I hope it makes sense. The [`ENTRYPOINT`](https://github.com/datasciencebr/jarbas/blob/master/Dockerfile#L35) suggested by @caduvieira might have killed [Celery](https://github.com/datasciencebr/jarbas/blob/master/docker-compose.yml#L28) **and** the [Gunicorn used for the production setup](https://github.com/datasciencebr/jarbas/blob/master/docker-compose.prod.yml#L15).

@anaschwendler and @caduvieira: a quick fix is feasible in the next few hours or should I completely revert the merge as a temporary fix?

**Comment by caduvieira** [comment]
I will look into it now

**Comment by cuducos** [comment]
> I will look into it now

Many many thanks. I'm online, available fo pairing. Just drop a line if I can be of any help.

**Comment by anaschwendler** [comment]
Many thanks @caduvieira !
