### ISSUE TITLE
Rename .xz to .csv.xz

### ISSUE THREAD

**Issue by turicas** [datasciencebr/jarbas#298]
**What is the problem?**
When we uncompress a file using the command `xz -d file.xz` the uncompressed file name will be `file`. It'd be good to have the files named `xxx.csv.xz` instead of `xxx.xz` so some software (which depends on file extension) will work properly.

**How can this be addressed?**
1) Replace lines like this (see `serenata_toolbox/chamber_of_deputies/dataset.py`):
```python
            .replace('.csv', '.xz') \
```
with:

```python

            .replace('.csv', '.csv.xz') \
```
This also happens on `serenata_toolbox/federal_senate/dataset.py` and maybe in other places.

2) Will also need to change all places where these files are read.

**Who could help with this issue?**
@cuducos?

**Labels**
[enhancement]

**Comment by cuducos** [comment]
Moving it to `serenata-toolbox` repo ; )
