### ISSUE TITLE
Try lower `random_page_cost` on Postgres

### ISSUE THREAD

**Issue by cuducos** [datasciencebr/jarbas#301]
**What is the problem?**
A bottleneck for Jarbas is Postgres performance. [This article](https://amplitude.engineering/how-a-single-postgresql-config-change-improved-slow-query-performance-by-50x-85593b8991b0) suggests that setting `random_page_cost ` lower works well when using SSD (which is our case).

**How can this be addressed?**
First compare some queries (special the ones from the Jarbas Dashboard) execution time with `random_page_cost=4` (default) and `random_page_cost=1`. If it really works, we need to adapt our Docker architecture to start the service with that custom setting.

**Who could help with this issue?**
Not sure… maybe @caduvieira? @fredgcosta?

**Comment by caduvieira** [comment]
Does the performance improved?

**Comment by cuducos** [comment]
> Does the performance improved?

Yep. I just ran simple tests locally and it was slightly quicker — nothing so surprising as in the reference, but worth it ; )

**Comment by caduvieira** [comment]
There are other recommendations on https://speakerdeck.com/ongres/postgresql-configuration-for-humans

**Comment by cuducos** [comment]
Closed by #303
