### ISSUE TITLE
Session freezing

### ISSUE THREAD

**Issue by jhonthan** [datasciencebr/jarbas#34]
Ao efetuar uma consulta por partido por exemplo, ao navegar pelas páginas a consulta congela, impossibilitando navegar nas páginas, nem mesmo o menu ao lado funciona, sendo necessário limpar a URL e começar novamente, que novamente congela entre 3-4 consulta.

**Comment by cuducos** [comment]
@jhonthan can you share the URL where you are getting freezing status?

**Comment by jhonthan** [comment]
@cuducos jarbas.datasciencebr.com/#/page/4/party/PR
Consigo ir somente até a página 4.

**Comment by cuducos** [comment]
Yuck! That's a 🐛

I see it on the console already:

```
Error: Ran into a `Debug.crash` in module `Documents.Supplier` on line 115
The message provided by the code author is:

    BadResponse 404 "Not Found"
```

Actually I left this case marked as `Debug.crash` to fix it later, but I haven't got back to it. Gonna fix soon. Thanks for the heads up 👍

**Comment by cuducos** [comment]
Hey @jhonthan — can you confirm it's working now?

**Comment by jhonthan** [comment]
@cuducos Sim, está funcionado :+1:

**Comment by cuducos** [comment]
Yay 🎉
