### ISSUE TITLE
Search by CEAP document # is not a good idea…

### ISSUE THREAD

**Issue by cuducos** [datasciencebr/jarbas#5]
… because it looks like `document_id` is not unique 😮

@irio, as this repo emerged from an issue you raised, how would **you** like to search for documents and company info here?

**Comment by cuducos** [comment]
Just to clarify (and ask for some code review, as I'm a newbie to Pandas):



```python
import numpy as np
import pandas as pd
dtype = {
    'document_id': np.str,
    'congressperson_id': np.str,
    'congressperson_document': np.str,
    'term_id': np.str,
    'cnpj_cpf': np.str,
    'reimbursement_number': np.str
}
data1 = pd.read_csv('../data/2016-08-08-current-year.xz', parse_dates=[16], dtype=dtype)
data2 = pd.read_csv('../data/2016-08-08-last-year.xz', parse_dates=[16], dtype=dtype)
data3 = pd.read_csv('../data/2016-08-08-previous-years.xz', parse_dates=[16], dtype=dtype)
data = pd.concat([data1, data2, data3])
```


```python
data['document_id'].value_counts()
```




    5880780    8
    5888894    7
    5888126    7
    5895939    7
    5888003    7
    5566496    7
    2444690    7
    5906123    6
    5001425    6
    5883832    6
    5881541    6
    5894465    5
    2455096    5
    5001008    5
    5980516    5
    5883511    5
    5582192    5
    2455061    5
    5576550    5
    5868186    5
    2450557    5
    5003212    5
    5586510    4
    5805399    4
    5894054    4
    5580525    4
    5884395    4
    5578531    4
    2453929    4
    5716890    4
              ..
    5198908    1
    6034395    1
    5025761    1
    2399737    1
    5829184    1
    5527888    1
    2171266    1
    5801504    1
    5047780    1
    5622885    1
    2173725    1
    2400020    1
    5173638    1
    5139407    1
    5205576    1
    5688364    1
    5501502    1
    2133265    1
    5538914    1
    5395696    1
    5944324    1
    2394718    1
    2328097    1
    2334778    1
    2434959    1
    5799615    1
    5416659    1
    5594715    1
    6042883    1
    2301787    1
    Name: document_id, dtype: int64

**Comment by cuducos** [comment]
And, yet, there are tons of records w/o `document_id`:

```python
pd.Series(
    (row.year, row.document_id)
    for row in data.itertuples()
).value_counts()
```

```
(2011, nan)        167133
(2013, nan)        165141
(2015, nan)        164976
(2012, nan)        156947
(2014, nan)        155135
(2016, nan)         72983
(2010, nan)         53020
(2009, nan)         37056
(2015, 5880780)         8
(2015, 5888894)         7
(2012, 2444690)         7
(2015, 5888003)         7
(2014, 5566496)         7
(2015, 5888126)         7
(2015, 5895939)         7
(2015, 5906123)         6
(2015, 5881541)         6
(2012, 5001425)         6
(2015, 5883832)         6
(2015, 5868186)         5
(2014, 5582192)         5
(2012, 2455096)         5
(2012, 2450557)         5
(2012, 5001008)         5
(2015, 5883511)         5
(2015, 5894465)         5
(2014, 5576550)         5
(2012, 2455061)         5
(2012, 5003212)         5
(2016, 5980516)         5
                    ...  
(2011, 2091886)         1
(2016, 6021165)         1
(2015, 5830813)         1
(2014, 5582842)         1
(2014, 5442616)         1
(2016, 5957922)         1
(2013, 5067949)         1
(2016, 6019270)         1
(2016, 6023921)         1
(2015, 5612208)         1
(2015, 5662710)         1
(2015, 5847708)         1
(2016, 5955356)         1
(2014, 5442164)         1
(2012, 2342119)         1
(2011, 2067390)         1
(2013, 5196686)         1
(2014, 5422886)         1
(2013, 5210042)         1
(2013, 5271328)         1
(2012, 2345521)         1
(2014, 5428073)         1
(2015, 5868380)         1
(2012, 2288150)         1
(2011, 2215236)         1
(2011, 2018182)         1
(2016, 5947613)         1
(2011, 2114782)         1
(2016, 5951307)         1
(2011, 2127011)         1
dtype: int64
```

**Comment by Irio** [comment]
Returning more than a single document is not a real issue for the current use case, @cuducos. Also, from the existing 101,333 records, just 69 are not unique (source of this calculation at the end of this comment).

If the server accepts filters for `document_id`, `congressperson_id` and `cnpj_cpf` I'm more than happy already.

```python
import pandas as pd

def read_csv(name):
    return pd.read_csv('data/2016-08-08-%s.xz' % name)


datasets = [read_csv(name)
            for name in ['current-year', 'last-year', 'previous-years']]
datasets = pd.concat(datasets)
len(datasets) - len(datasets['document_id'].unique()) # 69
```
