### ISSUE TITLE
Jarbas and machine learning results

### ISSUE THREAD

**Issue by cuducos** [datasciencebr/jarbas#52]
I'm documenting here the next steps of Jarbas in terms of development, i.e. it's a big issue, not a tiny and specific one. 

We have a new player in Serenata de Amor operation that is [Rosie](https://github.com/datasciencebr/rosie/). She's our robot, she'll tell us what she thinks of each reimbursement. Basically for each [hypothesis of our roadmap](https://github.com/datasciencebr/serenata-de-amor/milestones) Rosie will:

1. Say that for each reimbursement uniquely identified by a certain combination of `year`, `applicant_id` and`document_id` there is the a `probability` of irregularity/immorality/illegality (i.e. `0 < probability < 1`) .
2. Send a HTTP `POST` request to Jarbas with this `probability` and an some meta information of the hypothesis this probability refers to.

Thus Jarbas should be able to: [(removed in favor of this list)]( https://github.com/datasciencebr/jarbas/issues/52#issuecomment-266132576)

Conceptually this means that Jarbas is moving from _an internal tool_ to help people engaged in Serenata de Amor to a _public data visualization platform_ to a share our artificial intelligence  machine learning results with the world. A lot of changes (refactor, renaming, endpoints etc.) are expected 🎉

**Comment by cuducos** [comment]
This just started at [`next`](https://github.com/datasciencebr/jarbas/tree/next) branch ; )

**Comment by cuducos** [comment]
I just reslized the TODO list from the previous post changed considerably, so I'm gonna edit the post, remove the previous TODO list and use this one ro keep track of the progress:

- [ ] Create a new `Reimbursement` model to fit the new `YYYY-MM-DD-reimbursements.xz`
- [ ] Add fields to that model to store data about suspicions Rosie might find
- [ ] Add the current `Receipt` logic to `Reimbursement`
- [ ] Create list and detail API views for `Reimbursement`
- [ ] Create list API view for `/api/subquota/`
- [ ] Create list API view for `/api/applicant/`
- [ ] Apply filter for filtering in all three list API views
- [ ] Create command to read `YYYY-MM-DD-reimbursements.xz`
- [ ] Create command to read `YYYY-MM-DD-irregularities.xz` (generated by Rosie)
- [ ] Use cache in API views
- [ ] Adapt the front-end to new data structure
- [ ] Cleanup: remove old models, serializers, views, tests etc.

**Comment by cuducos** [comment]
Hi @daneoshiga: The changes described in that Issue will break compatibility with [tapioca-jarbas](https://github.com/daneoshiga/tapioca-jarbas/) (check the `README.md` from the `next` branch for more details). So I'm tagging you here in case you want to coordinate an update to your repo — we can make it happen ; )

**Comment by daneoshiga** [comment]
Thanks for the heads up, I'll keep keep an eye in the evolution of it and update tapioca-jarbas accordingly, thanks :)

**Comment by cuducos** [comment]
@daneoshiga soon I'm merging `next` to `master`, so the new API will be available. However until we write the new front-end #61 the old API still working because our current front-end consumes it. No need to hurry, but anyway: if you wanna pair I can learn bits of tapioca and maybe we both can solve it quicker ; )

**Comment by cuducos** [comment]
Closed by #64

**Comment by daneoshiga** [comment]
@cuducos sorry for taking too long to reply.
We could do that :), I have free time at night these days, but tapioca-wrapper is pretty easy to work with, just listing the new endpoints in resource_mapping.py should work :)
