### ISSUE TITLE
Expose more resources through the API (Jarbas)

### ISSUE THREAD

**Issue by rphlfc** [datasciencebr/jarbas#58]
It is more like a question than an actual issue but here it goes. Are you guys planning on exposing more resources through the API? The reason I am asking this is because as of right now the only method available is /api/document which lists Document objects. The thing is, each of the documents listed have attributes that could be referred to by their id's, state and party are examples of such. Then we could have both /api/states and /api/parties, respectively, to list the states and the parties.

The reason I am asking this is because I am planning on writing a wrapper in either objective-c or java to consume this information. By doing this someone else (or even me) could use it to write an app similar to 'Meu deputado' that could list the expenses, and its details, for any given congressperson. 

Here are my suggestions for new methods:
/api/states
/api/parties
/api/congresspeople

With at least these new methods I could start working on something more meaningful. 

Let me know what you guys think. I really appreciate what you guys are doing and would like to contribute somehow.

**Comment by cuducos** [comment]
Hi @rphlfc 

You can have all these filters right now, just use `conhressperson_id`, `party` and `state` keywords
 in the URL of `/api/document/` endpoint as mentioned in the `README.md` — does that make sense or did I get you wrong?

**Comment by gurgelrenan** [comment]
@cuducos is still possible search by `state`? I tried something like `https://jarbas.serenatadeamor.org/api/reimbursement/?subquota_id=13&state=ce` But didn't work

**Comment by cuducos** [comment]
> @cuducos is still possible search by `state`? 

No, [`state` is not listed as a filtering field](https://github.com/datasciencebr/jarbas#filtering); but no special reason for that — feel free to implement if you like. 

Alternativelly [use the Dashboard](https://jarbas.serenatadeamor.org/dashboard/core/reimbursement/?state=CE&subquota_id=13), it's way better for searching ; )
