### ISSUE TITLE
Load the datasets into our Postgres

### ISSUE THREAD

**Issue by cuducos** [datasciencebr/jarbas#6]
cc @lucavgobbi @pablov

A new `loaddatasets` is online:

```console
$ python manage.py loaddatasets --help
usage: manage.py loaddatasets [-h] [--version] [-v {0,1,2,3}]
                              [--settings SETTINGS] [--pythonpath PYTHONPATH]
                              [--traceback] [--no-color] [--start START]
                              [--limit LIMIT]

Load Serenata de Amor datasets into the database

optional arguments:
  -h, --help            show this help message and exit
  --version             show program's version number and exit
  -v {0,1,2,3}, --verbosity {0,1,2,3}
                        Verbosity level; 0=minimal output, 1=normal output,
                        2=verbose output, 3=very verbose output
  --settings SETTINGS   The Python path to a settings module, e.g.
                        "myproject.settings.main". If this isn't provided, the
                        DJANGO_SETTINGS_MODULE environment variable will be
                        used.
  --pythonpath PYTHONPATH
                        A directory to add to the Python path, e.g.
                        "/home/djangoprojects/myproject".
  --traceback           Raise on CommandError exceptions
  --no-color            Don't colorize the command output.
  --start START, -s START
                        Where the load should start (skips first LIMIT
                        documents)
  --limit LIMIT, -l LIMIT
                        Limit the number of documents to load
```
Basically with the optional arguments `--start` and `--limit` we can split the task of loading tons of data to our Postgres. For example, `python manage.py loaddatasets --start 1000 --limit 50` will only create/update the records number 1000 until 1049.

I once estimated we have ~2,7 million records. Running it locally is slower, but the script tends to run for a longer time. Running it at Heroku is quicker, but I guess Heroku drops the connection after a while.

I'll try to write a Python or shell script with a `for` loop to run this `loaddatasets` 1k records by 1k records at Heroku. But I'm open to new ideas ; )

**Comment by cuducos** [comment]
Running the script from commit e39f75d — gonna keep you updated.

**Comment by cuducos** [comment]
It takes roughly 7min30 to load 1000 records:

* 10s for Heroku to respond to the `heroku run`
* 6min15 to load 1000 records
* 1min (sleep between one execution and another)

We need approx. 2100 rounds of execution. If I'm not wrong, it is basically 10,5 days.

Not the best strategy ever but at least this is stable.

I can edit the script to start from round _x_ (e.g. say my connection is down after 752 executions, I can start from the 753 round).

The only alternative I can think about now is if someone try to load all that in a local Postgres and dump the data, so we can try to load this dump direct to the database.

**Comment by cuducos** [comment]
I added a line in the footer with the percentage of the dataset loaded. Currently it says _8% of CEAP data loaded_, confirming my estimative of ~10 days to have the full dataset available.

We cannot split this job among various people because Heroku free plan just allow one _dyno_ (one process, to make it simple even if not precise) at a time.

@irio and @cabral: I feel like that 10 days might be too much since this tool was suppose to free Irio from that task of looking for info on specific documents.

The reasonable alternative is to pay US$ 9/month for a better Postgres plan at Heroku (most of the waiting time is Heroku talking to a remote Postgres in a AWS EC2 instance).

Another alternative is to try to load the dataset into a local Postgres, dump a massive file and try to upload it to EC2 Postgres — not sure if timeout or any kind of other limits (RAM?) might be an issue there.

**Comment by Irio** [comment]
@cuducos Yes, I agree that 10 days may be too much time to have the service working. I'd counter recommend Heroku's database because will probably be much more expensive than plain AWS. Loading the dataset locally and generating a dump sounds a good approach for me.

Anyways, PostgreSQL has a documentation page giving tips on populating databases with keeping performance. Take a look specially on the `COPY` command. https://www.postgresql.org/docs/current/static/populate.html

**Comment by cuducos** [comment]
Many thanks, @Irio — from your advice I ended up in [Django's `bulk_insert`](https://docs.djangoproject.com/en/1.10/ref/models/querysets/#bulk-create). Now I'm able to insert 5k at a time (to keep memory usage in _safe_ levels), and this takes roughly 15s. In less than 2h all the dataset will be available at Jarbas.
