### ISSUE TITLE
Issue with 'Document value' presentation

### ISSUE THREAD

**Issue by luizfzs** [datasciencebr/jarbas#67]
By going through http://jarbas.datasciencebr.com/#/party/PMDB, I noticed the values of 'Document value' are presented like ##.###. As we use English, it should be like ##.###,##: 1) use '.' as thousands separator; 2) ',' for decimal separators; 3) use only 2 decimal places. By spotting` Document value "60.000" ` I interpret like a spending of R$ 6000,00 instead of R$ 60,00 like is on the receipt.

**Comment by cuducos** [comment]
Many thanks, @luizfzs — this was one of those things that it was supposed to be fixed later and ended up forgotten. I'm glad for the heads up. Soon we're deploying the fix ; )
