### ISSUE TITLE
Dates presented are off by one in relation to the date of the receipt

### ISSUE THREAD

**Issue by fgrehm** [datasciencebr/jarbas#93]
Looks like something in the client side based on the API response 🤔

<img width="606" alt="screen shot 2016-12-27 at 2 08 50 pm" src="https://cloud.githubusercontent.com/assets/81859/21503393/44c2d684-cc3e-11e6-8fce-0bbc679e97b0.png">

**Comment by Irio** [comment]
Probably caused by a [`Date.parse()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse) in GMT and conversion to negative timezone.

**Comment by cuducos** [comment]
The decoding is done using [`new Date(str)`](https://github.com/elm-lang/core/blob/5.0.0/src/Native/Date.js#L7) not the parser… very bizarre… starting to investigate now. Thanks for the heads up @fgrehm!

**Comment by cuducos** [comment]
@Irio nailed it:

```javascript
> new Date('2015-10-05');
< Sun Oct 04 2015 21:00:00 GMT-0300 (BRT)
```

I'm gonna drop the `Date` type and use an improvised one just with regular `Int` numbers… ugly and dirty but… does anyone have a better idea?

**Comment by Irio** [comment]
`new Date(dateString)` does an implicit call to `Date.parse(dateString)`.

```js
new Date(dateString + ' (BRT)')
```
should solve the bug.

**Comment by cuducos** [comment]
Yay! `(BRT)` didn't work, but you pointed me to the right direction:

```javascript
> new Date("2015-10-05T12:00:00-03:00")
< Mon Oct 05 2015 12:00:00 GMT-0300 (BRT)
```
