### ISSUE TITLE
Painful development with docker

### ISSUE THREAD

**Issue by petriuslima** [datasciencebr/jarbas#98]
When I was developing in docker environment, I felt that the development was painful because the following issues:
- Folders are copied when docker starts. So, any modification isn't  "on the fly"
- Elm container ends after executing gulp for the first time
- Jarbas container has the command to collectstatics after the update by elm container. So I had to execute the command manually every time that gulp executes

**Comment by cuducos** [comment]
I haven't used Docker for dev in Jarbas yet, but the critique makes a lot of sense. Unfortunately as a newbie in Docker I'm not sure about the best strategy to address this issue — any idea @petriuslima? 

Would #18 be the only possible solution?

**Comment by cuducos** [comment]
Also in spite of the title of this issue the problem is developing in Elm (frontend) or also in Python (backend)? May I add "with Elm" to make the title clearer?

**Comment by petriuslima** [comment]
I didn't test python container itself, but I think that the same occurs because the entire folder is copied to container. So, any change made in the real folder don't affect the folder inside the container.

**Comment by cuducos** [comment]
Thanks, @petriuslima. What about my first comment? Any idea? I feel kind of lost when it cames to Docker…

**Comment by rogeriochaves** [comment]
AFAIK, we could share local volumes with the docker containers on `docker-compose.yml`, for example:

```yaml
elm:
    build:
      context: .
      dockerfile: Dockerfile-elm
    volumes:
      - "assets:/assets/"
      - ".:/root"
```
(Dockerfile-elm doesn't have a WORKDIR, I don't know if it is copying all the files to /root, I just assumed)

But this should be only for development, we could have a `docker-compose.dev.yml` or call the current one `docker-compose.prod.yml`.

IMHO it is very good to develop using docker (when it is well configured for that), specially in this case since I don't know much about python, just want to see it running. It also helps getting a closer-to-prod environment since we would be reusing the (almost) the same Dockerfiles and docker-compose configs.

**Comment by cuducos** [comment]
I'm sorry I cannot address this issue right now as I'm a total newbie in Docker. I'm really glad @gomex, @gwmoura and @pedrommone have made important contribution in the direction of fixing an important issue: the deployment process, which is still very manual (wired up by a git hook in the production server). 

All that just to say: I totally agree with @rogeriochaves, _it is very good to develop using docker_. But unfortunately the maintainers of Jarbas need help when it comes to Docker, and the Docker instance itself started as a tool to automate deploy.

I hope this explain a bit of the context of the issue — even if it doesn't help in addressing the issue itself ; )

**Comment by gomex** [comment]
Hey @petriuslima ! 

Thanks for your feedback:

> Folders are copied when docker starts. So, any modification isn't "on the fly"

We can solve this mount our code to container:

https://github.com/datasciencebr/jarbas/pull/114
https://github.com/datasciencebr/jarbas/pull/113

> Elm container ends after executing gulp for the first time

How can we solve that? Is there other way?

> Jarbas container has the command to collectstatics after the update by elm container. So I had to execute the command manually every time that gulp executes

But this is design, right? Without docker you still need to collect that, right?

**Comment by cuducos** [comment]
> But this is design, right? Without docker you still need to collect that, right?
 
If you run Django in debug mode (this is what people do in development) you can skip `collectstatic`. But not sure if we can mimic that in a Docker environment. Debug mode is active when `.env` (or envvar) `DEBUG` equals `True`.

**Comment by gomex** [comment]
@cuducos you are right. We need to solve that part of collectstatic :( I will think about something

**Comment by gomex** [comment]
@cuducos to run django in debug mode we just need to have a environment variable DEBUG=True? If yes get my PR to solve this problem:

#115

**Comment by cuducos** [comment]
Great! I added minor comments to the PR, once you've checked them I merge it!

BTW #113 and #114 already merged.

**Comment by gomex** [comment]
@cuducos #115 updated. Can you please check again?

**Comment by cuducos** [comment]
Many thanks, @gomex 🎊 

@petriuslima After this 3 merged PR (#113, #114 and #115), can you update this issue highlighting what is still painful in the Docker development env so we can target it in a more specific way?

**Comment by gomex** [comment]
@cuducos thanks! 

@petriuslima I am here to help you. I am not developer, because that may be it is not good yet.

**Comment by petriuslima** [comment]
Hey guys, sorry for my absence!

@cuducos 
> Would #18 be the only possible solution?

I think no. We have solutions without spliting the repositories. But, it would be a good thing to do in the future.

@rogeriochaves great suggestions. The Docker Compose have some ways to extend the files too.

@gomex Nice, man. I didn't test everything, but the docker-compose.yml looks pretty good. I don't know much about python and elm development, so I can test only for my use case.

@cuducos The `Debug=True` is to Django collect the files automatically? If yes, what we need to do @gomex is make sure that elm container still running, but I don't know the best approach, I read only `while true` and `tail -f` examples :/

**Comment by cuducos** [comment]
> @cuducos The Debug=True is to Django collect the files automatically?

Yes… but not exactly. Let's say it's a side effect.

The idea of the debug mode is to make it easier to develop — which includes other features besides the bypass of `collectstatic` as reloading the server once any `.py` file is changed or completely disabling CSRF.

In the debug mode Django itself serves the static files for you, directly, which is a terrible idea (performance-wise) for production. In production the `collectstatic` puts them all together in a separate folder so you can serve them directly from the file system through nginx, for example — way faster.

**Comment by cuducos** [comment]
Not sure if it helps but I just remember there is the `npm run watch` command that watches for any changes in `**/*.Elm` and re-compile the `app.js` on the fly. Maybe using this command instead of `npm run assets` might help — but I'm not sure about how to code that to the first in development and the second on production.

**Comment by gomex** [comment]
Hey @petriuslima 

> @gomex is make sure that elm container still running, but I don't know the best approach, I read only while true and tail -f examples :/

Until we find a better way for that I created a make target to run ELM again:

`make build.elm`

**Comment by gomex** [comment]
> Not sure if it helps but I just remember there is the npm run watch command that watches for any changes in **/*.Elm and re-compile the app.js on the fly. Maybe using this command instead of npm run assets might help — but I'm not sure about how to code that to the first in development and the second on production.

We can replace the command inside docker-compose.yml, because we will use different docker-compose file to put in prod.

Can you tell the exact command I need to run?

**Comment by cuducos** [comment]
Yay. So here we go:

* `npm run watch` for development
* `npm run assets` for production

**Comment by gomex** [comment]
@cuducos PR #126

**Comment by cuducos** [comment]
Merged!

**Comment by gomex** [comment]
Hey @petriuslima

Can you test again?

**Comment by petriuslima** [comment]
@gomex, 
The Elm container was still stopping on start process, so I fix that (was some problem with shared volumes, as described by the commit c4305c93e9eefaa644de75570fc3300877ad9127, if you want to see) and do some changes to allow the development of dev and prod environment. The best way I tought is using docker compose extends but for now I think this should work.

@cuducos and @gomex, I think that the command for `Debug=True` was not working. The Elm container is refreshing the `app.js` (with some seconds of delay because of the time to process the changes) but I had to run the `collectstatic` to update the files in Jarbas container. I guess that if the `staticfiles` volume from Jarbas container was shared with Elm container and in the `gulpfile.js` the elm task put the `app.js` in this shared volume instead of in `jarbas/frontend/static/app.js`, it should works. Could this have any side-effects?

**Comment by gomex** [comment]
@petriuslima I hope the PR #127 solve that. Let's wait @cuducos merge that.

**Comment by cuducos** [comment]
> @cuducos and @gomex, I think that the command for `Debug=True`

Minor detail: it should be `DEBUG=True` not `Debug=True` but I guess in the file it was right.

Anyway… not sure if debug mode is active? Let's check if then:

* Jump in Jarbas directory inside the container (the directory that has the `manage.py` file)
* Enter `python manage.py shell -c 'from django.conf import settings; print(settings.DEBUG)'`

You will see `True` or `False` in the console ; )

Was debug mode active or nor in your environment?

**Comment by cuducos** [comment]
We just merged #127 that should have made dev in Docker a bit easier — tou @gomex. Can you guys test and feedback? Many thanks

**Comment by fcevado** [comment]
just tested it.... and got:
![error](https://cloud.githubusercontent.com/assets/9992984/24318890/6f7b4210-10ec-11e7-9212-ce2ec0588674.png)

**Comment by cuducos** [comment]
Closing this issue to focus discussion on that topic on #163
